name: Run Selenium Tests

on:
  push:
    branches:
      - dev3
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb  

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: List Repository Files
      run: |
        echo "Listing files in repository..."
        ls -R
        echo "Current Directory: $(pwd)"

    - name: Pause for Verification Code
      run: echo "Manually enter verification code"
      timeout-minutes: 10  # Wait for 10 minutes

    - name: Run Tests with Virtual Display
      run: xvfb-run -a python -m unittest tests/test_checklist.py

    - name: Upload Screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: artifacts/screenshots  # Ensure this matches the actual folder path

    - name: Upload HTML Artifact
      uses: actions/upload-artifact@v3
      with:
        name: page-source
        path: page_source.html  # Ensure this matches the actual file path
