name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Chrome Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Run Tests
      env:
        CHROME_USER_DIR: ./data/cash1
      run: |
        mkdir -p $CHROME_USER_DIR
        python -m unittest test_checklist.py
