  name: Run Selenium Tests

  on:
    push:
      branches:
        - dev2
    pull_request:

  jobs:
    selenium-tests:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

#      - name: Unzip Chrome Cache to Default Directory
#        run: |
#          mkdir -p ~/.config/google-chrome/Default
#          unzip /home/runner/work/SLPUI/SLPUI/data/cash.zip -d ~/.config/google-chrome/Default
  

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Pause for Verification Code
        run: echo "Manually enter verification code"
        timeout-minutes: 10  # Wait for 10 minutes

      - name: Run Tests with Virtual Display
        run: xvfb-run -a python -m unittest tests/test_checklist.py

      - name: Archive Chrome Cache
        run: zip -r cache_archive.zip ~/.cache/google-chrome/Default

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-cache
          path: cache_archive.zip

      - name: Upload Screenshots
        if: failure()  # Only upload if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots
